export { default as Home } from "./Home"
export { default as Courses } from "./Courses"
export { default as CourseSyllabus } from "./CourseSyllabus"
export { default as IMAT } from "./IMAT"
export { default as Universities } from "./Universities"
export { default as Blogs } from "./Blogs"
export { default as Blog } from "./Blog"
export { default as About } from "./About"
export { default as StudyAbroad } from "./StudyAbroad"
export { default as Consultation } from "./Consultation"

export {default as TermsAndServices} from "./utility-pages/TermsAndServices"
export {default as PrivacyPolicy} from "./utility-pages/PrivacyPolicy"
export { default as PageNotFound } from "./utility-pages/PageNotFound"